export interface Project {
    slug: string
    title: string
    url: string
    role: string
    tags: string[]
    category: 'wordpress' | 'react' | 'laravel' | 'design'
    featured?: boolean
  }
  
  export const projects: Project[] = [
    {
      slug: 'nerkhito',
      title: 'Nerkhito Platform',
      url: 'https://nerkhito.ir/',
      role: 'Co-Founder, Design and Support',
      tags: ['WordPress', 'Plugin Development', 'Custom Theme'],
      category: 'wordpress',
      featured: true,
    },
    {
      slug: 'otaghak-blog',
      title: 'Otaghak Blog',
      url: 'https://www.otaghak.com/blog/',
      role: 'Technical Support',
      tags: ['WordPress', 'Custom Theme'],
      category: 'wordpress',
      featured: true,
    },
    {
      slug: 'dalili-group',
      title: 'Dalili Group',
      url: 'https://daliligroup.com/',
      role: 'Design and Technical Support',
      tags: ['WordPress', 'Plugin Development', 'Custom Theme'],
      category: 'wordpress',
      featured: true,
    },
    {
      slug: 'ibamo',
      title: 'Ibamo Store',
      url: 'https://ibamo.ir/',
      role: 'Design and Technical Support',
      tags: ['WordPress', 'Plugin Development', 'Custom Theme'],
      category: 'wordpress',
    },
    {
      slug: 'sorme-beauty',
      title: 'Sorme Beauty Directory',
      url: 'http://sormebeauty.com/',
      role: 'Design',
      tags: ['WordPress', 'Plugin Development', 'Custom Theme'],
      category: 'wordpress',
    },
    {
      slug: 'msi-farsi',
      title: 'MSI Farsi',
      url: 'https://msifarsi.com/',
      role: 'Design and Technical Support',
      tags: ['WordPress', 'Community', 'Custom Theme'],
      category: 'wordpress',
      featured: true,
    },
    {
      slug: 'msi-club',
      title: 'MSI Club',
      url: 'https://club.msifarsi.com/',
      role: 'Technical Support',
      tags: ['Laravel', 'Membership', 'CSS'],
      category: 'laravel',
    },
    {
      slug: 'mirrogene',
      title: 'Mirrogene',
      url: 'https://mirrogene.com/',
      role: 'Design and Technical Support',
      tags: ['WordPress', 'Health', 'CSS'],
      category: 'wordpress',
    },
    {
      slug: 'mirrogene-panel',
      title: 'Mirrogene Panel',
      url: 'https://panel.mirrogene.com/',
      role: 'Design and Technical Support',
      tags: ['Laravel', 'Dashboard', 'Admin'],
      category: 'laravel',
      featured: true,
    },
    {
      slug: 'unique-cut',
      title: 'Unique Cut',
      url: 'https://uniquecut.ca/',
      role: 'Design',
      tags: ['WordPress', 'CSS', 'Responsive'],
      category: 'design',
    },
    {
      slug: 'cyra-beauty',
      title: 'Cyra Beauty',
      url: 'https://cyrabeauty.ca/',
      role: 'Design',
      tags: ['WordPress', 'WooCommerce', 'CSS'],
      category: 'design',
    },
    {
      slug: 'chameleon-bc',
      title: 'Chameleon BC',
      url: 'https://chameleonbc.com/',
      role: 'Design',
      tags: ['WordPress', 'Elementor', 'CSS'],
      category: 'design',
    },
    {
      slug: 'simply-travel',
      title: 'Simply Travel & Tour',
      url: 'https://simplytravelandtour.com/',
      role: 'Design',
      tags: ['WordPress', 'Booking System', 'CSS'],
      category: 'design',
    },
    {
      slug: 'unex-safety',
      title: 'Unex Safety',
      url: 'https://unexsafety.com/',
      role: 'Design',
      tags: ['WordPress', 'WooCommerce', 'CSS'],
      category: 'design',
    },
    {
      slug: 'rangineh',
      title: 'Rangineh Decoration',
      url: 'https://ranginehdecoration.ir/',
      role: 'Design',
      tags: ['WordPress', 'CSS', 'Portfolio'],
      category: 'design',
    },
    {
      slug: 'hub-game',
      title: 'Hub Game Store',
      url: 'https://hubgamestore.com/',
      role: 'Design and Technical Support',
      tags: ['WordPress', 'WooCommerce', 'Digital Products'],
      category: 'wordpress',
    },
    {
      slug: 'pejvak',
      title: 'Pejvak Co',
      url: 'https://pejvakco.com/',
      role: 'Design',
      tags: ['WordPress', 'Business', 'CSS'],
      category: 'design',
    },
    {
      slug: 'parchat',
      title: 'Parchat',
      url: 'https://parchat.net/',
      role: 'Design and Technical Support',
      tags: ['WordPress', 'Real-time', 'Custom Theme'],
      category: 'wordpress',
      featured: true,
    },
    {
      slug: 'owj-digital',
      title: 'Owj Digital',
      url: 'https://owjdigital.com/',
      role: 'Design',
      tags: ['WordPress', 'Agency', 'Portfolio'],
      category: 'design',
    },
    {
      slug: 'sadatpour',
      title: 'Sadatpour Portfolio',
      url: 'https://sadatpour.dev/',
      role: 'Design and Technical Support',
      tags: ['React', 'TypeScript', 'Tailwind CSS'],
      category: 'react',
      featured: true,
    },
  ]
  
  export const featuredProjects = projects.filter(p => p.featured)